// File: barrel_shifter.v
// Generated by MyHDL 0.11
// Date: Fri Oct  1 02:56:55 2021


`timescale 1ns/10ps

module barrel_shifter (
    load_value,
    load_input,
    shift_reg
);


output [11:0] load_value;
wire [11:0] load_value;
input [11:0] load_input;
input [2:0] shift_reg;





assign load_value = (load_input >>> shift_reg);

endmodule
