// File: alu.v
// Generated by MyHDL 0.11
// Date: Wed Sep 29 17:14:25 2021


`timescale 1ns/10ps

module alu (
    a,
    b,
    sel,
    output
);


input [2:0] a;
input [2:0] b;
input [2:0] sel;
output [2:0] output;
reg [2:0] output;




always @(b, sel, a) begin: ALU_ALU
    case (sel)
        'h0: begin
            output = (a + b);
        end
        'h1: begin
            output = (a - b);
        end
        'h2: begin
            output = (a & b);
        end
        'h3: begin
            output = (a | b);
        end
        default: begin
            output = (a ^ b);
        end
    endcase
end

endmodule
