// File: decoder.v
// Generated by MyHDL 0.11
// Date: Sat Sep 25 04:06:43 2021


`timescale 1ns/10ps

module decoder (
    i0,
    i1,
    d0,
    d1,
    d2,
    d3
);


input i0;
input i1;
output d0;
reg d0;
output d1;
reg d1;
output d2;
reg d2;
output d3;
reg d3;




always @(i0, i1) begin: DECODER_DECODER_2TO4
    if (((i1 == 0) && (i0 == 0))) begin
        d0 = 1;
        d1 = 0;
        d2 = 0;
        d3 = 0;
    end
    else if (((i1 == 0) && (i0 == 1))) begin
        d0 = 0;
        d1 = 1;
        d2 = 0;
        d3 = 0;
    end
    else if (((i1 == 1) && (i0 == 0))) begin
        d0 = 0;
        d1 = 0;
        d2 = 1;
        d3 = 0;
    end
    else begin
        d0 = 0;
        d1 = 0;
        d2 = 0;
        d3 = 1;
    end
end

endmodule
