// File: mux_2to1.v
// Generated by MyHDL 0.11
// Date: Sat Sep 25 04:28:01 2021


`timescale 1ns/10ps

module mux_2to1 (
    i0,
    i1,
    sel,
    out
);


input i0;
input i1;
input sel;
output out;
reg out;




always @(i1, i0, sel) begin: MUX_2TO1_MUX2TO1
    if ((sel == 0)) begin
        out = i0;
    end
    else begin
        out = i1;
    end
end

endmodule
