// File: Counter.v
// Generated by MyHDL 0.11
// Date: Fri Oct  1 21:39:58 2021


`timescale 1ns/10ps

module Counter (
    count,
    enable,
    clk,
    reset
);
// #count -- output
// #enable -- control input, increment when 1
// #clk -- clock input
// #reset -- asynchronous reset input

output [11:0] count;
reg [11:0] count;
input enable;
input clk;
input reset;




always @(posedge clk, negedge reset) begin: COUNTER_COUNTER
    if (reset == 0) begin
        count <= 0;
    end
    else begin
        if (enable) begin
            count <= (count + 1);
        end
    end
end

endmodule
