// File: decoder.v
// Generated by MyHDL 0.11
// Date: Fri Oct  1 21:09:10 2021


`timescale 1ns/10ps

module decoder (
    i0,
    i1,
    d0,
    d1,
    d2,
    d3
);


input [0:0] i0;
input [0:0] i1;
output [0:0] d0;
wire [0:0] d0;
output [0:0] d1;
wire [0:0] d1;
output [0:0] d2;
wire [0:0] d2;
output [0:0] d3;
wire [0:0] d3;





assign d0 = ((~i1) & (~i0));
assign d1 = ((~i1) & i0);
assign d2 = (i1 & (~i0));
assign d3 = (i1 & i0);

endmodule
